### ISSUE TITLE
Share a movie option for going to the cinema

### ISSUE THREAD

**Issue by markusfisch** [marcelgross90/Cineaste#25]
Have an easy way to share a movie with social media or other apps via Android's share menu to plan a night at the cinema. Including a link to the movie description and even the poster? And maybe even local cinema times (by adding a google query for "[name of the movie] cinema")?

**Comment by marcelgross90** [comment]
Next release will have the share menu.

This allows you to share the name of the movie/series and a link to this at theMovieDb
