### ISSUE TITLE
Missing padding on movie card between action buttons and border

### ISSUE THREAD

**Issue by markusfisch** [marcelgross90/Cineaste#6]
At least on my device (Android 4.4.2) there's no padding around the action buttons on the right side of a movie card:

![screenshot_2016-10-23-13-43-38](https://cloud.githubusercontent.com/assets/485246/19626165/382987e2-992b-11e6-80b5-bc8099e800a2.png)

**Comment by marcelgross90** [comment]
Thank you for your report. 
There shouldn't be a padding at the top and the bottom as well. 
![screenshot_20161023-154839](https://cloud.githubusercontent.com/assets/7499630/19626774/83757316-9938-11e6-84c4-748ce6eaa54e.png)
